version: '3.8'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - pg:/var/lib/mysql/
volumes:
  pg:
